src/StudentAssessmentTool/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
	url(r'^website/', include('website.urls')),
    url(r'^admin/', admin.site.urls),
]

src/website/urls.py
from django.conf.urls import url, include
from . import views

app_name = 'website'

urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^register/$', views.RegisterUserView.as_view(), name='register'),
	url(r'^login/$', views.LoginUserView.as_view(), name='login'),
	url(r'^logout/$', views.logout_view, name='logout'),
	url(r'^student/$', views.student_view, name='student'),
	url(r'^teacher/$', views.teacher_view, name='teacher'),
	url(r'^feedback/$', views.FeedbackView, name='feedback'),
	# url(r'^student/performance/$', views.performance_view, name='performance'),
	# url(r'^student/feedback/$', views.feedback_view, name='feedback'),
	# url(r'^student/material/$', views.material_view, name='material'),
]

src/website/models.py
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save

# Create your models here.
class UserProfile(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='user')
	designation = models.CharField(default='', blank=True, max_length=50)

	def __str__(self):
		return self.user.first_name + ' ' + self.user.last_name + ' : ' + self.designation

def create_profile(sender, **kwargs):
    user = kwargs["instance"]
    if kwargs["created"]:
        user_profile = UserProfile(user=user)
        user_profile.save()

post_save.connect(create_profile, sender=User)			

class StudentMarks(models.Model):
	rollNo = models.CharField(max_length=10) #Student's Roll Number
	# student = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, default=User())
	name = models.CharField(max_length=50, default='')
	mq1 = models.IntegerField() #Midsem Question 1
	mq2 = models.IntegerField() #Midsem Question 2
	mq3 = models.IntegerField() #Midsem Question 3
	mlq = models.IntegerField() #Midsem Lab Question
	eq1 = models.IntegerField() #Endsem Question 1
	eq2 = models.IntegerField() #Endsem Question 2
	eq3 = models.IntegerField() #Endsem Question 3
	eq4 = models.IntegerField() #Endsem Question 4
	elq = models.IntegerField() #Endsem Lab Question
	assignment = models.FloatField() #Assignment
	project = models.FloatField() #Project

class Department(models.Model):
	dept_name = models.CharField(max_length=200)
	hod = models.CharField(max_length=200)
	num_of_labs = models.IntegerField()

	def __str__(self):
		return self.dept_name

class Course(models.Model):
	course_code = models.CharField(max_length=10)
	course_name = models.CharField(max_length=200)
	dept = models.ForeignKey(Department, on_delete=models.CASCADE)
	instructor = models.CharField(max_length=200)

	def __str__(self):
		return self.course_code + ':' + self.course_name

class Feedback(models.Model):
	course = models.ForeignKey(Course, on_delete=models.CASCADE)
	feedback = models.CharField(max_length=1000)
	student = models.ForeignKey(UserProfile, on_delete=models.CASCADE)

	def __str__(self):
		return self.course.course_code + ' : ' + self.course.course_name

src/website/forms.py
from django.contrib.auth.models import User
from .models import Feedback,Course
from django import forms

CHOICES=[('student','Student'),
         ('teacher','Teacher')]


class RegisterForm(forms.ModelForm):
	password = forms.CharField(widget=forms.PasswordInput)
	designation = forms.ChoiceField(choices=CHOICES, widget=forms.RadioSelect())
	class Meta:
		model = User
		fields = ['username', 'email', 'first_name', 'last_name', 'password', 'designation']

class LoginForm(forms.ModelForm):
	password = forms.CharField(widget=forms.PasswordInput)
	class Meta:
		model = User
		fields = ['username', 'password']

class FeedbackForm(forms.ModelForm):
	course = forms.ModelChoiceField(queryset=Course.objects.all(), empty_label=None, to_field_name='course_code')
	class Meta:
		model = Feedback
		fields = ['course','feedback']

src/website/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout 
from django.shortcuts import render, redirect
from django.views.generic import View 
from .forms import RegisterForm, LoginForm, FeedbackForm
from .models import UserProfile, StudentMarks, Feedback, Course
from django.urls import reverse

# Create your views here.
def index(request):
	return render(request, 'website/index.html')

def logout_view(request):
	logout(request)
	return redirect('website:index')

def student_view(request):
	form = FeedbackForm(None)
	if request.user.is_authenticated():
		return render(request, 'website/student_profile.html', {'marks': StudentMarks.objects.get(name=request.user.first_name),'form': form})
	else:
		return redirect('website:login')

def teacher_view(request):
	if request.user.is_authenticated():
		return render(request, 'website/teacher_profile.html', {'students': StudentMarks.objects.all(), 'feedbacks': Feedback.objects.filter(course=Course.objects.get(instructor=request.user.username))})
	else:
		return redirect('website:login')		

class RegisterUserView(View):
	form_class = RegisterForm
	template_name = 'website/registration_form.html'

	# display blank form
	def get(self, request):
		form = self.form_class(None)
		return render(request, self.template_name, {'form': form})

	# process form data
	def post(self, request):
		form = self.form_class(request.POST)

		if form.is_valid():

			# does not save to database, just creates form object
			user = form.save(commit=False)

			# cleaned, normalized data
			username = form.cleaned_data['username']
			password = form.cleaned_data['password']
			user.set_password(password)
			user.save()

			#returns User objects if credentials are correct
			user = authenticate(username=username, password=password)
			if user is not None:
				if user.is_active:
					login(request, user)
					designation = form.cleaned_data['designation']
					# to use user details on page
					# request.user.username , request.user.designation , etc.
					if designation == 'student':
						return redirect(reverse('website:student'))
					else:
						return redirect('website:teacher')

		return render(request, self.template_name, {'form': form})

class LoginUserView(View):
	form_class = LoginForm
	template_name = 'website/login_form.html'

	# display blank form
	def get(self, request):
		form = self.form_class(None)
		return render(request, self.template_name, {'form': form})

	# process form data
	def post(self, request):
		username = request.POST['username']
		password = request.POST['password']
		user = authenticate(username=username, password=password)
		if user is not None:

			login(request, user)

			if user.user.designation == 'student':
				return redirect(reverse('website:student'))
			else:
				return redirect(reverse('website:teacher'))

		else:

			return redirect('website:login')


def FeedbackView(request):
	if request.method == 'POST':		
		form = FeedbackForm(request.POST)
		if form.is_valid():
			# does not save to database, just creates form object
			feedback = form.save(commit=False)
			feedback.student = UserProfile.objects.get(user=request.user)
			feedback.save()
	return redirect('website:student')

src/website/templates/website/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
	<title>{% block pagetitle %}{% endblock %}</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'website/css/bootstrap.min.css' %}" />
    <link href="https://fonts.googleapis.com/css?family=Indie+Flower" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Fredericka+the+Great" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="{% static 'website/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'website/js/d3.min.js' %}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.5.0/Chart.min.js"></script>
</head>
<body>

	<!-- Navbar -->
	<nav class="navbar navbar-inverse navbar-fixed-top" style="margin-bottom: 0px; font-size: 1.5em;">
		<div class="container-fluid">

		<!-- Logo -->
		<div class="navbar-header">
			<a href="{% url 'website:index' %}" class="navbar-brand" style="font-size: 2em; font-family: 'Fredericka the Great', cursive;">Classroom</a>
		</div>

		<!-- Menu Items -->

		<div>
			<ul class="nav navbar-nav">
				<li class="active"><a href="{% url 'website:index' %}">Home</a></li>
				<li><a href="#about">About</a></li>
				<li><a href="#contact">Contact</a></li>
			</ul>

			<ul class="nav navbar-nav navbar-right">
				{% if not request.user.is_authenticated %}
					<li><a href="{% url 'website:register' %}">Register</a></li>
					<li><a href="{% url 'website:login' %}">Login</a></li>
				{% else %}
					{% if request.user.user.designation == 'student' %}
						<li><a href="{% url 'website:student' %}">Class</a></li>
					{% else %}
						<li><a href="{% url 'website:teacher' %}">Class</a></li>
					{% endif %}

					<li><a href="{% url 'website:logout' %}">Logout</a></li>
				{% endif %}
			</ul>
		</div>

		</div>
	</nav>

	{% block content %}
	{% endblock %}

</body>
</html>

src/website/templates/website/form_template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

src/website/templates/website/index.html
	
{% extends 'website/base.html' %}

{% load staticfiles %}

{% block pagetitle %}Classroom{% endblock %}
    

{% block content %}
	<div class="jumbotron" style="padding-top: 110px; margin: 0px; border: 0px; background-image: url({% static 'website/classroom.jpg' %}); background-size: cover; height: 100vh; text-align: center;">
		<h1 style="margin-top: 0px;">Hello there!</h1>
		<p>Welcome to the Student Assessment Tool</p>
		<p><a class="btn btn-primary btn-lg" href="#about" role="button">Learn more</a></p>
	</div>
	<div class="container-fluid" id="about">
		<div class="row">
			<div class="col-md-4 col-md-offset-4 text-center" style="padding-top:60px;">
				<h2>About</h2>
			</div>
			<div class="col-md-8 col-md-offset-2 text-justify" style="padding-top: 40px; padding-bottom: 60px;">
				<p class="lead">
					<strong>Classroom</strong> is an interactive Student Assessment Tool for E-Learning and Classroom Response System. It is targeted towards a wide educational audience of Learners, Instructors, Developer and Expert Analyzer. It allows the learner access to learning materials and resources provided by the instructors. Also, it allows them to gain knowledge and closely monitor their learning path and activities. It allows the learners to share resources amongst each other for combined studies. It has a useful feedback system. Learners can also monitor and evaluate their progress.
				</p>
			</div>
		</div>
		<div class="row" style="background-color: #3B653D; color: white; font-family: 'Fredericka the Great', cursive; padding-top:100px; padding-bottom: 100px;">
			<div class="col-md-3" style="text-align: center;">
				<span class="glyphicon glyphicon-search" aria-hidden="true" style="font-size: 80px; color: white;"></span><br/><br/><br/>
				<h3 class="text-center">Search Learning Material</h3>
			</div>
			<div class="col-md-3" style="text-align: center;">
				<span class="glyphicon glyphicon-ok" aria-hidden="true" style="font-size: 80px; color: white;"></span><br/><br/><br/>
				<h3 class="text-center">Evaluate Performance</h3>
			</div>
			<div class="col-md-3" style="text-align: center;">
				<span class="glyphicon glyphicon-pencil" aria-hidden="true" style="font-size: 80px; color: white;"></span><br/><br/><br/>
				<h3 class="text-center">Provide Feedback</h3>
			</div>
			<div class="col-md-3" style="text-align: center;">
				<span class="glyphicon glyphicon-education" aria-hidden="true" style="font-size: 80px; color: white;"></span><br/><br/><br/>
				<h3 class="text-center">Graduate with Flying Colours</h3>
			</div>
		</div>
	</div>
	<div class="container-fluid" id="contact"  style="background-color: #DDDDDD;">
		<div class="row">
			<div class="col-md-4 col-md-offset-4 text-center" style="padding-top:60px;">
				<h2>Contact</h2>
			</div>
		</div>
		<div class="row">
			<div class="col-md-4 col-md-offset-4 text-center"  style="padding-top:40px;">
				<address>
				  <strong>Classroom, Inc.</strong><br>
				  D317, Mega Tower 2<br>
				  NITK, Surathkal - 575025<br>
				  <abbr title="Phone">Ph:</abbr> +91 9611638180
				</address>

				<address>
				  <strong>Samyak Jain</strong><br>
				  <a href="mailto:samyak24jain@gmail.com">samyak24jain@gmail.com</a>
				</address>
			</div>			
		</div>
		<div class="row text-justify">
			<div class="col-md-1 col-md-offset-4">
				<p><a href="#about">About</a></p>
			</div>
			<div class="col-md-1">
				<p><a href="https://github.com/samyak24jain/Student-Assessment-Tool">GitHub</a></p>
			</div>
			<div class="col-md-1">
				<p><a href="https://www.facebook.com/samyak24jain">Facebook</a></p>
			</div>
			<div class="col-md-1">
				<p><a href="https://in.linkedin.com/in/samyak24jain">LinkedIn</a></p>
			</div>
		</div>
	</div>
{% endblock %}

src/website/templates/website/login_form.html
{% extends 'website/base.html' %}

{% block pagetitle %}Login{% endblock %}

{% block content %}
<div class="container-fluid" style="margin-top: 100px;">

    <div class="row">

        <div class="col-sm-12 col-md-4 col-md-offset-4">
            <div class="panel panel-default">
                <div class="panel-body" style="display: block; text-align: center;">
                    <h3>Login</h3><hr>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data" style="display: inline-block;">
                        {% csrf_token %}
                        {% include 'website/form_template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>

    </div>

</div>
{% endblock %}

src/website/templates/website/registration_form.html
{% extends 'website/base.html' %}

{% block pagetitle %}Create a new Account{% endblock %}

{% block content %}
<div class="container-fluid" style="margin-top: 100px;">

    <div class="row">

        <div class="col-sm-12 col-md-4 col-md-offset-4">
            <div class="panel panel-default">
                <div class="panel-body" style="display: block; text-align: center;">
                    <h3>Register</h3><hr>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data" style="display: inline-block;">
                        {% csrf_token %}
                        {% include 'website/form_template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>

    </div>

</div>
{% endblock %}

src/website/templates/website/student_profile.html
{% extends 'website/base.html' %}

{% load staticfiles %}

{% block pagetitle %}{{ user.first_name }} | Classroom{% endblock %}

{% block content %}

<div class="container-fluid">
	<div class="row text-center" style="margin-top: 110px;">
		<div class="col-md-8 col-md-offset-2">
			<ul class="nav nav-tabs">
			  <li class="active"><a data-toggle="tab" href="#performance">Evaluate Performance</a></li>
			  <li><a data-toggle="tab" href="#feedback">Feedback</a></li>
			  <li><a data-toggle="tab" href="#material">Learning Material</a></li>
			</ul>

			<div class="tab-content">
			  <div id="performance" class="tab-pane fade in active">
			    <h3>Evaluate Performance</h3>
			    <canvas id="myChart" width="400" height="200" style="border:1px solid #000000;"> </canvas>
			  </div>
			  <div id="feedback" class="tab-pane fade">
			    <h3>Feedback</h3>
			    <form class="form-horizontal" role="form" action="{% url 'website:feedback' %}" method="post" enctype="multipart/form-data" style="display: inline-block;">
			    	{% csrf_token %}
			        {% include 'website/form_template.html' %}
			        <div class="form-group">
			            <div class="col-sm-offset-2 col-sm-10">
			                <button type="submit" class="btn btn-success">Submit</button>
			            </div>
			        </div>
			    </form>
			  </div>
			  <div id="material" class="tab-pane fade">
			    <h3>Learning Material</h3>
			    <p>Learning resources and material.</p>
			  </div>
			</div>	
		</div>
	</div>


	<script type="text/javascript">
	
		function plot() {
			var graphData = [{{marks.mq1}}, {{marks.mq2}}, {{marks.mq3}}, {{marks.mlq}}, {{marks.eq1}}, {{marks.eq2}}, {{marks.eq3}}, {{marks.eq4}}, {{marks.elq}}, {{marks.assignment}}, {{marks.project}},]
			var ctx = document.getElementById('myChart');
			var data = {
				labels:['Midsem Q1','Midsem Q2','Midsem Q3','Midsem Lab Q', 'Endsem Q1', 'Endsem Q2','Endsem Q3','Endsem Q4','Endsem Lab Q','Assignment','Project'], 
				datasets:[
						{
							data:graphData,
							label:'Marks Plot',
							backgroundColor: 'rgba(54, 162, 235, 0.2)',
				            borderColor: 'rgba(54, 162, 235, 1)',
				            borderWidth: 2,
				            fill: false,
						}
					],
			};
			var myLineChart = new Chart(ctx, {
			    type: 'line',
			    data: data,
			});
		};
		plot();

	</script>

</div>		
{% endblock %}

src/website/templates/website/teacher_profile.html
{% extends 'website/base.html' %}

{% load staticfiles %}

{% block pagetitle %}{{ user.first_name }} | Classroom{% endblock %}

{% block content %}

<div class="container-fluid">
	<div class="row text-center" style="margin-top: 110px;">
		<div class="col-md-8 col-md-offset-2">
			<ul class="nav nav-tabs">
			  <li class="active"><a data-toggle="tab" href="#students">Students</a></li>
			  <li><a data-toggle="tab" href="#feedback">Feedback</a></li>
			  <li><a data-toggle="tab" href="#material">Learning Material</a></li>
			</ul>

			<div class="tab-content">
			  <div id="students" class="tab-pane fade in active">
			    <h3>Students</h3>
			    <table class="table table-hover">
			      <tr>
			      	<th>Roll Number</th>
			      	<th>Student Name</th>
			      	<th>Midsem Theory</th>
			      	<th>Midsem Lab</th>
			      	<th>Endsem Theory</th>
			      	<th>Endsem Lab</th>
			      	<th>Project</th>
			      	<th>Assignment</th>
			      </tr>
			      {% for student in students %}
			      	<tr>
			      		<td>
			      			{{ student.rollNo }}
			      		</td>
			      		<td>
			      			{{ student.name }}
			      		</td>
			      		<td>
			      			{{ student.mq1|add:student.mq2|add:student.mq3 }}
			      		</td>
			      		<td>
			      			{{ student.mlq }}
			      		</td>
			      		<td>
			      			{{ student.eq1|add:student.eq2|add:student.eq3 }}
			      		</td>
			      		<td>
			      			{{ student.elq }}
			      		</td>
			      		<td>
			      			{{ student.project }}
			      		</td>
			      		<td>
			      			{{ student.assignment }}
			      		</td>
			      	</tr>
			      {% endfor %}
			    </table>
			  </div>
			  <div id="feedback" class="tab-pane fade">
			    <h3>Feedback</h3>
			    <table class="table table-hover">
			    	<tr>
			    		<th>
			    			Student Name
			    		</th>
			    		<th>
			    			Feedback
			    		</th>
			    	</tr>
			    	{% for feedback in feedbacks %}
				    	<tr>
				    		<td>{{ feedback.student.user.first_name }}</td>
				    		<td>{{ feedback.feedback }}</td>
				    	</tr>
				    {% endfor %}
			    </table>
			  </div>
			  <div id="material" class="tab-pane fade">
			    <h3>Learning Material</h3>
			    <p>Learning resources and material.</p>
			  </div>
			</div>	
		</div>
	</div>

</div>	

{% endblock %}